// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEgRsLkYuNjVA8CppgMukrMzGWZd4apyQ',
    appId: '1:327088604055:web:33e1c7f858d0bd5a3f3ad2',
    messagingSenderId: '327088604055',
    projectId: 'ucak-bileti-rezervasyon',
    authDomain: 'ucak-bileti-rezervasyon.firebaseapp.com',
    storageBucket: 'ucak-bileti-rezervasyon.firebasestorage.app',
    measurementId: 'G-MBZG2S0N3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGBukjLQESgV3DXgNxnBak0ze_qczGTPU',
    appId: '1:327088604055:android:310660ba5493031c3f3ad2',
    messagingSenderId: '327088604055',
    projectId: 'ucak-bileti-rezervasyon',
    storageBucket: 'ucak-bileti-rezervasyon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu1NfggLHs6994OMfocspJrk7xztn6iso',
    appId: '1:327088604055:ios:b1dfa308726735203f3ad2',
    messagingSenderId: '327088604055',
    projectId: 'ucak-bileti-rezervasyon',
    storageBucket: 'ucak-bileti-rezervasyon.firebasestorage.app',
    iosBundleId: 'com.example.203311057IbrahimfurkangulcanFlutterPreject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu1NfggLHs6994OMfocspJrk7xztn6iso',
    appId: '1:327088604055:ios:b1dfa308726735203f3ad2',
    messagingSenderId: '327088604055',
    projectId: 'ucak-bileti-rezervasyon',
    storageBucket: 'ucak-bileti-rezervasyon.firebasestorage.app',
    iosBundleId: 'com.example.203311057IbrahimfurkangulcanFlutterPreject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEgRsLkYuNjVA8CppgMukrMzGWZd4apyQ',
    appId: '1:327088604055:web:139e1a6415de6ece3f3ad2',
    messagingSenderId: '327088604055',
    projectId: 'ucak-bileti-rezervasyon',
    authDomain: 'ucak-bileti-rezervasyon.firebaseapp.com',
    storageBucket: 'ucak-bileti-rezervasyon.firebasestorage.app',
    measurementId: 'G-9F57XD4K1Y',
  );
}
